//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMessenger.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class msgctrlDev
    {
        public decimal msg_id { get; set; }
        public Nullable<System.DateTime> msg_entry { get; set; }
        public Nullable<System.DateTime> msg_date { get; set; }
        public string msg_by { get; set; }
        public string msg_section { get; set; }
        public string msg_phone { get; set; }
        public string msg_contact_name { get; set; }
        public string msg_company { get; set; }
        public string msg_address { get; set; }
        public string msg_telephone { get; set; }
        public string msg_map { get; set; }
        public string msg_send { get; set; }
        public string msg_receive { get; set; }
        public string msg_doctype { get; set; }
        public string msg_priority_normal { get; set; }
        public string msg_priority_urgent { get; set; }
        public Nullable<System.DateTime> msg_on_date { get; set; }
        public string msg_msg_name { get; set; }
        public string msg_close_status { get; set; }
        public Nullable<System.DateTime> msg_close_date { get; set; }
        public Nullable<System.DateTime> msg_close_time { get; set; }
        public string msg_close_by { get; set; }
        public string msg_remark { get; set; }
        public string msg_print_label { get; set; }
        public string msg_accept_by { get; set; }
        public Nullable<System.DateTime> msg_accept_date { get; set; }
        public string msg_edit_by { get; set; }
        public Nullable<System.DateTime> msg_edit_date { get; set; }
        public string msg_cancel_remark { get; set; }
    }
}
