//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMessenger.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string username { get; set; }
        public string password { get; set; }
        public string levels { get; set; }
        public string owner { get; set; }
        public string xsales { get; set; }
        public string name { get; set; }
        public string department { get; set; }
        public string section { get; set; }
        public string sc { get; set; }
        public string email { get; set; }
        public string destination { get; set; }
        public string section_group { get; set; }
        public string team_group { get; set; }
        public string sales_code { get; set; }
    }
}
